# image will be published to ghcr.io/<user>/<name>
name: sb-dx
# description will be included in the image's metadata
description: This is my personal Silverblue image with batteries included.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 40 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - etc: /etc
          # copies stuff to /etc that will be needed by the installer
      - usr: /usr
          # copies config/files/usr into your image's /usr.
          # put configuration files you want in /etc/ on a booted system
          # in /usr/etc/ in the image. read more in files module reference.

  # enable google-chrome repo and disable gpgcheck.
  # currently this seems to be the only sane way to install google-chrome.
  - type: script
    scripts:
      - google-chrome-fix.sh

  # override gschema
  - type: gschema-overrides
    include:
      - zz1-sb.gschema.override

  # install gnome-extensions
  - type: gnome-extensions
    install:
      - gnome-shell-go-to-last-workspacegithub.com.v13
      - logomenuaryan_k.v30

  # install fonts
  - type: fonts
    fonts:
      nerd-fonts:
        - JetBrainsMono

  # install system packages
  - type: rpm-ostree
    repos:
      # - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
    install:
      - alacritty
      - code
      - fish
      - gcc
      - gnome-console
      - gnome-shell-extension-pop-shell
      - google-chrome-stable
    optfix:
      - google
    remove:
      # example: removing firefox (in favor of the flatpak)
      # "firefox" is the main package, "firefox-langpacks" is a dependency
      # - firefox
      # - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)
      - gnome-terminal
      - gnome-terminal-nautilus
      - toolbox
      - tmux

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
